// Package domain defines the core Task and Schedule types shared by every backend.
//
// Nothing in this package talks to a database, a queue, or a network. It holds
// the vocabulary the rest of the system agrees on, so the Postgres and Redis
// backends cannot drift into two different ideas of what a task is.
package domain

import (
	"encoding/json"
	"time"
)

// Status is the lifecycle state of a task.
//
// The values are stored as text in Postgres rather than an enum type, because
// adding a value to a Postgres enum takes a lock that a busy tasks table cannot
// afford, and the readability win in psql is real.
type Status string

const (
	// StatusPending means the task is waiting to be claimed. It becomes
	// claimable once run_at has passed, as measured by the database clock.
	StatusPending Status = "pending"

	// StatusRunning means a worker holds the claim and is executing. The worker
	// must refresh heartbeat_at, or the sweeper will treat the task as orphaned.
	StatusRunning Status = "running"

	// StatusSucceeded means the handler returned nil. Terminal.
	StatusSucceeded Status = "succeeded"

	// StatusFailed means the handler returned an error and retries remain. This
	// is a transient state: the task is written straight back to pending with a
	// future run_at, so it exists mainly for attempt history.
	StatusFailed Status = "failed"

	// StatusDead means attempts reached max_attempts without success. Terminal,
	// and deliberately never cleaned up automatically. A dead task is evidence.
	StatusDead Status = "dead"

	// StatusCancelled means the task was cancelled before it was ever claimed.
	// Terminal. A running task cannot be cancelled; see Task.Cancellable.
	StatusCancelled Status = "cancelled"
)

// AllStatuses lists every valid status. Useful for validation and for metric
// label pre-registration, so a gauge reads zero rather than being absent.
func AllStatuses() []Status {
	return []Status{
		StatusPending, StatusRunning, StatusSucceeded,
		StatusFailed, StatusDead, StatusCancelled,
	}
}

// Valid reports whether s is a status this system recognises.
func (s Status) Valid() bool {
	switch s {
	case StatusPending, StatusRunning, StatusSucceeded,
		StatusFailed, StatusDead, StatusCancelled:
		return true
	default:
		return false
	}
}

// Terminal reports whether s is a final state that no transition leaves.
func (s Status) Terminal() bool {
	switch s {
	case StatusSucceeded, StatusDead, StatusCancelled:
		return true
	default:
		return false
	}
}

func (s Status) String() string { return string(s) }

// Task is one execution: a payload, a scheduled time, a status, and the retry
// metadata needed to decide what happens when it fails.
//
// Field order mirrors the tasks table so the struct and the schema can be
// diffed by eye.
type Task struct {
	// ID is the primary key, assigned by the database.
	ID int64 `json:"id"`

	// Queue partitions work. Workers claim from exactly one queue, so a slow
	// queue cannot starve a fast one.
	Queue string `json:"queue"`

	// Handler names the registered function that executes this task. The
	// scheduler never executes arbitrary code; it dispatches by name.
	Handler string `json:"handler"`

	// Payload is opaque to Tick. It is passed to the handler untouched.
	Payload json.RawMessage `json:"payload"`

	// Priority orders claiming, higher first. Ties break by run_at.
	Priority int `json:"priority"`

	// Status is the current lifecycle state.
	Status Status `json:"status"`

	// RunAt is the earliest instant this task may be claimed. Always compared
	// against the database clock, never a worker's clock.
	RunAt time.Time `json:"run_at"`

	// Attempts counts claims, incremented by the claim query itself. A task
	// claimed and then orphaned has still consumed an attempt, which is what
	// stops a task that reliably kills its worker from looping forever.
	Attempts int `json:"attempts"`

	// MaxAttempts is the ceiling after which the task moves to dead.
	MaxAttempts int `json:"max_attempts"`

	// ClaimedBy identifies the worker holding the claim, nil when unclaimed.
	ClaimedBy *string `json:"claimed_by,omitempty"`

	// HeartbeatAt is when the owning worker last proved it was alive.
	HeartbeatAt *time.Time `json:"heartbeat_at,omitempty"`

	// IdempotencyKey deduplicates submissions within a queue. For a task
	// generated by a schedule it is "schedule_id:run_at", which is what stops
	// two scheduler nodes from materializing the same fire time twice.
	IdempotencyKey *string `json:"idempotency_key,omitempty"`

	// ScheduleID links a materialized task back to the rule that created it.
	ScheduleID *int64 `json:"schedule_id,omitempty"`

	// LastError holds the most recent failure message, truncated.
	LastError *string `json:"last_error,omitempty"`

	// CreatedAt is set by the database on insert.
	CreatedAt time.Time `json:"created_at"`
}

// MaxLastErrorBytes bounds what is written to last_error. A handler that
// returns a megabyte-long error should not be able to bloat the tasks table.
const MaxLastErrorBytes = 4096

// TruncateError shortens an error message to fit last_error, marking it so a
// reader knows the text was cut rather than produced that way.
func TruncateError(msg string) string {
	const suffix = " ...[truncated]"
	if len(msg) <= MaxLastErrorBytes {
		return msg
	}
	return msg[:MaxLastErrorBytes-len(suffix)] + suffix
}

// Cancellable reports whether the task can still be cancelled. Only a task that
// no worker has claimed can be: once execution has begun, the side effects are
// already in flight and cancellation would be a lie.
func (t *Task) Cancellable() bool {
	return t.Status == StatusPending
}

// RetriesRemaining reports how many attempts are left before the task dies.
func (t *Task) RetriesRemaining() int {
	if n := t.MaxAttempts - t.Attempts; n > 0 {
		return n
	}
	return 0
}

// Exhausted reports whether this task has used its final attempt and should
// move to dead rather than back to pending.
func (t *Task) Exhausted() bool {
	return t.Attempts >= t.MaxAttempts
}

// Recurring reports whether this task was materialized from a schedule.
func (t *Task) Recurring() bool {
	return t.ScheduleID != nil
}

// Due reports whether the task is claimable at instant now.
//
// Callers must pass the database clock. This method exists for tests and for
// in-memory reasoning; the real claim decision is made inside the SQL statement
// using now(), because a single clock is the only defence against node drift.
func (t *Task) Due(now time.Time) bool {
	return t.Status == StatusPending && !t.RunAt.After(now)
}
